import PyInstaller.__main__
import os
import shutil

# This script bundles the Flask app and the React dist folder into one EXE.
# First, ensure you've run `npm run build` so the `dist` folder exists.

dist_dir = os.path.join(os.getcwd(), 'dist')
backend_file = os.path.join(os.getcwd(), 'backend', 'app.py')

if not os.path.exists(dist_dir):
    print("Error: 'dist' folder not found. Please run 'npm run build' first.")
    exit(1)

# PyInstaller command
PyInstaller.__main__.run([
    backend_file,
    '--onefile',
    '--windowed',
    '--name=AlankarBilling',
    f'--add-data={dist_dir}{os.pathsep}dist',
    '--distpath=release',
    '--clean',
    '--noconfirm'
])

print("\nBuild Complete! Check the 'dist' folder (within current directory, generated by PyInstaller) for AlankarBilling.exe")
